version: '3.4'

services:
  scimaterials.ui.mvc:
    container_name: mvc
    image: scimaterialsuimvc:latest
    restart: on-failure
    depends_on:
      - postgres_db
      - sqlserver_db
    build:
      context: .
      dockerfile: UI/SciMaterials.UI.MVC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - WebAPI=http://scimaterials.ui.mvc
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5185:80"
    volumes:
      - mvc:/var/lib/mvc/data/
    networks:
      - scimaterials_network
  
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql_auth/data/
    networks:
      - scimaterials_network
  
  sqlserver_db:
    container_name: sqlserver2019_db
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=veryStrongPassword123
    ports:
      - "1433:1433"
    volumes:
      - db:/var/lib/sqlserver2019/data/
    networks:
      - scimaterials_network

volumes:
  db:
  mvc:

networks:
  scimaterials_network:
    driver: bridge